# importing fresh_tomatoes.py to call its open_movies_page function  to pass list of the movies
import fresh_tomatoes
# importing media.py  to instantiate movie class objects 
import media 

miracles_from_heaven = media.Movie('Miracles from Heaven', 'The Beam family - Kevin (Martin Henderson), Christy (Jennifer Garner), and daughters Abbie (Brighton Sharbino), Annabel (Kylie Rogers), and Adelynn (Courtney Fansler) - live in Burleson, Texas. They frequently go to church on Sundays. The pastor Reverend Scott (John Carroll Lynch) gives a sermon on keeping your faith at all times.', 'https://yts.ag/assets/images/movies/miracles_from_heaven_2016/medium-cover.jpg', 'https://www.youtube.com/watch?v=CldGTG6iVrU')

zootopia=media.Movie('Zootopia', ' From the largest elephant to the smallest shrew, the city of Zootopia is a mammal metropolis where various animals live and thrive. When Judy Hopps becomes the first rabbit to join the police force, she quickly learns how tough it is to enforce the law. Determined to prove herself, Judy jumps at the opportunity to solve a mysterious case. Unfortunately, that means working with Nick Wilde, a wily fox who makes her job even harder. ', 'https://yts.ag/assets/images/movies/zootopia_2016/medium-cover.jpg', 'https://www.youtube.com/watch?v=yCOPJi0Urq4')

the_game_of_their_lives=media.Movie('The Game of Their Lives', ' Based on a true story, this film tells the tale of the 1950 US soccer team who, against all odds, beat England 1 - 0 in the city of Belo Horizonte, Brazil. Although no US team has ever won a World Cup title, this story is about the family traditions and passions which shaped the lives of the players who made up this team of underdogs. ', 'https://yts.ag/assets/images/movies/the_game_of_their_lives_2005/medium-cover.jpg', 'https://www.youtube.com/watch?v=PhcBQp9NFJI')

kung_fu_panda = media.Movie('Kung Fu Panda 3', ' When Pos long-lost panda father suddenly reappears, the reunited duo travels to a secret panda paradise to meet scores of hilarious new panda characters. But when the supernatural villain Kai begins to sweep across China defeating all the kung fu masters, Po must do the impossible-learn to train a village full of his fun-loving, clumsy brethren to become the ultimate band of Kung Fu Pandas. ', 'https://yts.ag/assets/images/movies/kung_fu_panda_3_2016/medium-cover.jpg', 'https://www.youtube.com/watch?v=10r9ozshGVE')

london_has_fallen= media.Movie('London Has Fallen', " After the British Prime Minister has passed away under mysterious circumstances, all leaders of the Western world must attend his funeral. But what starts out as the most protected event on earth, turns into a deadly plot to kill the world's most powerful leaders and unleash a terrifying vision of the future. The President of the United States, his formidable secret service head and a British MI-6 agent who trusts no one are the only people that have any hope of stopping it. ", 'https://yts.ag/assets/images/movies/london_has_fallen_2016/medium-cover.jpg', 'https://www.youtube.com/watch?v=MMbyPhQo75A')

toy_story = media.Movie('Toy Story','A story of a boy and his toys that come to life ','http://www.gstatic.com/tv/thumb/movieposters/17420/p17420_p_v8_ab.jpg','https://www.youtube.com/watch?v=ZZv1vki4ou4')

ride_along = media.Movie('Ride Along 2', " The RIDE ALONG 2 sequel picks up about a year after our heroes' last adventure. Plans for a quick trip to Miami go bad. With the wedding upcoming, James reluctantly takes Ben with him to Miami to follow up on a lead connected to a drug ring case he's been trying to crack. In Miami, they meet Maya, a no-BS homicide detective who lets them know Miami is her turf. They also encounter AJ, a shady cocky computer hacker who reveals evidence that implicates a well-respected local businessman, the wealthy Antonio Pope. Pope harbors a vicious streak and rules South Florida's drug trade. If Ben and James can convince the authorities that Pope is a brutal crime boss they'll stop his spree. If they fail, well there may not be a wedding after all. ", 'https://yts.ag/assets/images/movies/ride_along_2_2016/medium-cover.jpg', 'https://www.youtube.com/watch?v=2t5Q2SpaiNo')

norm_of_the_north = media.Movie('Norm of the North', ' When a real estate development invades his Arctic home, Norm and his three lemming friends head to New York City, where Norm becomes the mascot of the corporation in an attempt to bring it down from the inside and protect his homeland. ', 'https://yts.ag/assets/images/movies/norm_of_the_north_2016/medium-cover.jpg', 'https://www.youtube.com/watch?v=u8A_F5oYJGI')

eye_in_the_sky = media.Movie('Eye in the Sky', ' EYE IN THE SKY stars Helen Mirren as Colonel Katherine Powell, a UK-based military officer in command of a top secret drone operation to capture terrorists in Kenya. Through remote surveillance and on-the-ground intel, Powell discovers the targets are planning a suicide bombing and the mission escalates from "capture" to "kill." But as American pilot Steve Watts (Aaron Paul) is about to engage, a nine-year old girl enters the kill zone triggering an international dispute, reaching the highest levels of US and British government, over the moral, political, and personal implications of modern warfare. ', 'https://yts.ag/assets/images/movies/eye_in_the_sky_2015/medium-cover.jpg', 'https://www.youtube.com/watch?v=hOqeoj669xg')

movies=[miracles_from_heaven,zootopia,the_game_of_their_lives,kung_fu_panda,london_has_fallen,ride_along,norm_of_the_north,toy_story,eye_in_the_sky]

fresh_tomatoes.open_movies_page(movies)